# Generated by Django 4.2.7 on 2025-07-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('tunnel_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESP32Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.FloatField(blank=True, null=True)),
                ('param2', models.FloatField(blank=True, null=True)),
                ('param3', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('predicted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
