# Generated by Django 5.1.1 on 2024-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.FloatField(blank=True, null=True)),
                ('param2', models.FloatField(blank=True, null=True)),
                ('param3', models.FloatField(blank=True, null=True)),
                ('param4', models.FloatField(blank=True, null=True)),
                ('param5', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('predicted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
