# Generated by Django 4.2.7 on 2025-07-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32data',
            name='q_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esp32data',
            name='q_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esp32data',
            name='q_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esp32data',
            name='q_z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
