# Generated by Django 5.1.1 on 2024-09-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_param1_esp32data_accx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esp32data',
            old_name='accx',
            new_name='param1',
        ),
        migrations.RenameField(
            model_name='esp32data',
            old_name='accy',
            new_name='param2',
        ),
        migrations.RenameField(
            model_name='esp32data',
            old_name='accz',
            new_name='param3',
        ),
    ]
